cn: 
 springcloud: 
          book:
            test: I am the git configuration file from spring-cloud-config.yml test
            config: I am the git configuration file from spring-cloud-config.ym
